"""BGFA format constants."""

from __future__ import annotations

import logging

from pygfa.encoding.enums import (
    CigarDecomposition,
    IntegerEncoding,
    StringEncoding,
    WalkDecomposition,
)

BGFA_MAGIC = 0x41464742
BGFA_VERSION = 1
DEFAULT_BLOCK_SIZE = 1024

SECTION_ID_SEGMENTS = 2
SECTION_ID_LINKS = 3
SECTION_ID_PATHS = 4
SECTION_ID_WALKS = 5

INTEGER_ENCODING_NONE = IntegerEncoding.NONE
INTEGER_ENCODING_VARINT = IntegerEncoding.VARINT
INTEGER_ENCODING_FIXED16 = IntegerEncoding.FIXED16
INTEGER_ENCODING_FIXED32 = IntegerEncoding.FIXED32
INTEGER_ENCODING_FIXED64 = IntegerEncoding.FIXED64
INTEGER_ENCODING_DELTA = IntegerEncoding.DELTA
INTEGER_ENCODING_ELIAS_GAMMA = IntegerEncoding.ELIAS_GAMMA
INTEGER_ENCODING_ELIAS_OMEGA = IntegerEncoding.ELIAS_OMEGA
INTEGER_ENCODING_GOLOMB = IntegerEncoding.GOLOMB
INTEGER_ENCODING_RICE = IntegerEncoding.RICE
INTEGER_ENCODING_STREAMVBYTE = IntegerEncoding.STREAMVBYTE
INTEGER_ENCODING_VBYTE = IntegerEncoding.VBYTE
INTEGER_ENCODING_IDENTITY = IntegerEncoding.IDENTITY

STRING_ENCODING_NONE = StringEncoding.NONE
STRING_ENCODING_IDENTITY = StringEncoding.IDENTITY
STRING_ENCODING_ZSTD = StringEncoding.ZSTD
STRING_ENCODING_GZIP = StringEncoding.GZIP
STRING_ENCODING_LZMA = StringEncoding.LZMA
STRING_ENCODING_HUFFMAN = StringEncoding.HUFFMAN
STRING_ENCODING_2BIT_DNA = StringEncoding.TWO_BIT_DNA
STRING_ENCODING_ARITHMETIC = StringEncoding.ARITHMETIC
STRING_ENCODING_BWT_HUFFMAN = StringEncoding.BWT_HUFFMAN
STRING_ENCODING_RLE = StringEncoding.RLE
STRING_ENCODING_DICTIONARY = StringEncoding.DICTIONARY
STRING_ENCODING_ZSTD_DICT = StringEncoding.ZSTD_DICT
STRING_ENCODING_LZ4 = StringEncoding.LZ4
STRING_ENCODING_BROTLI = StringEncoding.BROTLI
STRING_ENCODING_PPM = StringEncoding.PPM

WALK_DECOMPOSITION_NONE = WalkDecomposition.NONE
WALK_DECOMPOSITION_ORIENTATION_STRID = WalkDecomposition.ORIENTATION_STRID
WALK_DECOMPOSITION_ORIENTATION_NUMID = WalkDecomposition.ORIENTATION_NUMID

CIGAR_DECOMPOSITION_NONE = CigarDecomposition.NONE
CIGAR_DECOMPOSITION_NUM_OPS_LENGTHS_OPS = CigarDecomposition.NUM_OPERATIONS
CIGAR_DECOMPOSITION_STRING = CigarDecomposition.STRING

logger = logging.getLogger(__name__)
